# Site settings
title: '#play14'
email: team@play14.org
description: > # this means to ignore newlines until "baseurl:"
  We believe in playfulness.
  An international gathering for people who share the idea that playing is a great way to teach, learn and understand!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://play14.org" # the base hostname & protocol for your site
twitter_username: play14team
github_username:  play14team

# Build settings
markdown: kramdown

paginate: 4
paginate_path: "blog/page:num"

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
#   - jekyll-mentions
#   - jemoji

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
#  - jekyll-mentions

#jekyll-mentions:
#  base_url: https://twitter.com

collections:
  events:
    output: true
  games:
    output: true
    permalink: :collection/:path
  players:
    output: true
    permalink: :collection/:path

defaults:
  - scope:
      path: "/events"
      type: "events"
    values:
      layout: "event"
  - scope:
      path: "/games"
      type: "games"
    values:
      layout: "game"
  - scope:
      path: "/players"
      type: "players"
    values:
      layout: "player"

permalink: pretty

emptyArray: []